### PR TITLE
fix: udpate sentry to allow replays and update deps

### LINKED ISSUE #65: Update sentry and deps

### PR DESCRIPTION
**Pull request by spaenleh**
This PR udpates sentry to suport Replays and generally updates dependencies to latest versions

closes #65

### CODE REVIEW

File: src/components/repl/Repl.tsx [hunk 1]
```diff
@@ -38,8 +32,8 @@ import OutputConsole from './OutputConsole';
 import ReplToolbar from './ReplToolbar';
 import ShowFigures from './ShowFigures';
 
-const OutlineWrapper = styled(Box)(
-  sx({
+const OutlineWrapper = styled(Box)(({ theme }) =>
+  theme.unstable_sx({
```
Comment (dialexo) [inline src/components/repl/Repl.tsx:36]: What is `unstable_sx` as opposed to `sx`?

File: package.json [hunk 2]
```diff
@@ -11,27 +11,27 @@
...
+    "@codemirror/lang-python": "6.1.1",
     "@emotion/react": "11.10.5",
     "@emotion/styled": "11.10.5",
     "@fortawesome/fontawesome-svg-core": "6.2.1",
     "@fortawesome/free-regular-svg-icons": "6.2.1",
     "@fortawesome/free-solid-svg-icons": "6.2.1",
-    "@fortawesome/react-fontawesome": "latest",
-    "@graasp/apps-query-client": "github:graasp/graasp-apps-query-client#v0",
+    "@fortawesome/react-fontawesome": "0.2.0",
+    "@graasp/apps-query-client": "^0.4.1",
```
Comment (dialexo) [inline package.json:22]: Should we use the caret notation or not? It would make sense to pin for consistency, but we'll have to add renovatebot to ensure that they are brought up-to-date

This also applies to all our other graasp deps

File: package.json [hunk 3]
```diff
@@ -87,26 +87,26 @@
...
   },
   "devDependencies": {
-    "@commitlint/cli": "17.2.0",
-    "@commitlint/config-conventional": "17.2.0",
+    "@commitlint/cli": "17.4.0",
+    "@commitlint/config-conventional": "17.4.0",
     "@cypress/code-coverage": "3.10.0",
     "@cypress/instrument-cra": "1.4.0",
-    "@trivago/prettier-plugin-sort-imports": "3.4.0",
+    "@trivago/prettier-plugin-sort-imports": "4.0.0",
```
Comment (dialexo) [inline package.json:94]: I don't expect this major update to break stuff, but just to make sure, do the prettier commands still work?

File: package.json [hunk 4]
```diff
@@ -87,26 +87,26 @@
...
-    "@types/i18n": "0.13.5",
+    "@types/i18n": "0.13.6",
     "@types/lodash.countby": "4.6.7",
     "@types/lodash.isequal": "4.5.6",
     "@types/lodash.isobject": "3.0.7",
     "@types/lodash.isstring": "4.0.7",
-    "@types/uuid": "8.3.4",
-    "@typescript-eslint/eslint-plugin": "5.43.0",
-    "@typescript-eslint/parser": "5.43.0",
+    "@types/uuid": "9.0.0",
```
Comment (dialexo) [inline package.json:101]: Can this major update break our stuff?

File: package.json [hunk 5]
```diff
@@ -87,26 +87,26 @@
...
+    "@typescript-eslint/eslint-plugin": "5.48.0",
+    "@typescript-eslint/parser": "5.48.0",
     "concurrently": "7.6.0",
-    "cypress": "11.1.0",
+    "cypress": "12.3.0",
```
Comment (dialexo) [inline package.json:105]: Similarly, I guess this does not break the cypress tests?

File: package.json [hunk 6]
```diff
@@ -115,13 +115,13 @@
...
-    "husky": "8.0.2",
+    "husky": "8.0.3",
     "nyc": "15.1.0",
-    "prettier": "2.7.1",
+    "prettier": "2.8.1",
     "pretty-quick": "3.1.3",
     "standard-version": "9.5.0",
     "uuid": "9.0.0",
-    "wait-on": "6.0.1"
+    "wait-on": "7.0.1"
```
Comment (dialexo) [inline package.json:124]: Can this major update break our stuff?

**Review by dialexo — APPROVED** [review]
I've left a few questions mostly regarding dependencies. Let me know what you think, otherwise LGTM :guitar:

File: src/components/repl/Repl.tsx (hunk 1 above)
Comment (spaenleh) [reply src/components/repl/Repl.tsx:36]: It lets you use the [`sx` syntax inside the styled utility or directly inside the theme](https://mui.com/material-ui/customization/theme-components/#the-sx-syntax-experimental). It just got renamed from `experimental_sx` imported from `@mui/material` [see before the change](https://github.com/graasp/graasp-app-code-capsule/blob/bee611c7a08cbc6763fd247fd459926f36bfeff5/src/components/repl/Repl.tsx#L12) to `theme.unstable_sx`

File: package.json (hunk 2 above)
Comment (spaenleh) [reply package.json:22]: Right I think we should pin, will update.

👍 for Renovatebot

File: package.json (hunk 3 above)
Comment (spaenleh) [reply package.json:94]: [The `v4.0.0` changelog](https://github.com/trivago/prettier-plugin-sort-imports/releases/tag/v4.0.0) does not seem to mention breaking changes

File: package.json (hunk 5 above)
Comment (spaenleh) [reply package.json:105]: No, it is safe to update from 10 to 11 and to 12. Breaking changes occurred when migrating from v9 to v10 (migration guides and code migration tools made the process significantly smoother, well done Cypress 🎉 ). 
Major advantage of using v11 over v10 is the startup speed improvement and v12 added better cookie support and other cool features.

File: package.json (hunk 6 above)
Comment (spaenleh) [reply package.json:124]: From the [release notes for v7.0.0](https://github.com/jeffbski/wait-on/releases/tag/v7.0.0) they updates dependencies which means support Node 12.x was dropped. This should not break our stuff.
