### PR TITLE
fix: add tooltips to repl buttons

### LINKED ISSUE #18: Add tooltips to repl buttons

### PR DESCRIPTION
**Pull request by spaenleh**
This PR adds tooltips to repl buttons.

Screenshot 2022-11-16 at 16 47 06

closes #18

### CODE REVIEW

File: src/components/layout/MiniButton.tsx [hunk 1]
```diff
@@ -52,30 +55,38 @@ const MiniButton: FC<Props> = ({
...
+    <Tooltip title={tooltip}>
+      <span>
+        <IconButton
+          color={color}
+          disabled={disabled || isLoading}
+          data-cy={dataCy}
+          id={id}
+          onClick={onClick}
+        >
+          {isLoading ? <CircularProgress size={24} /> : icon}
```
Comment (juancarlosfarah) [inline src/components/layout/MiniButton.tsx:86]: Factor out this inn another PR, eventually.

File: src/langs/en.json [hunk 2]
```diff
@@ -124,6 +124,10 @@
     "Upload Data Files": "Upload Data Files",
     "No files": "No files",
     "Supported formats": "Supported formats: {{formats}}",
-    "Pre-loaded libraries": "Pre-loaded libraries"
+    "Pre-loaded libraries": "Pre-loaded libraries",
+    "Stop Execution": "Stop Execution",
+    "Clear outputs and figures": "Clear outputs and figures",
```
Comment (juancarlosfarah) [inline src/langs/en.json:129]:
```suggestion
    "Clear outputs and figures": "Clear Outputs and Figures",
```

File: src/langs/en.json [hunk 3]
```diff
@@ -124,6 +124,10 @@
     "Upload Data Files": "Upload Data Files",
     "No files": "No files",
     "Supported formats": "Supported formats: {{formats}}",
-    "Pre-loaded libraries": "Pre-loaded libraries"
+    "Pre-loaded libraries": "Pre-loaded libraries",
```
Comment (juancarlosfarah) [inline src/langs/en.json:127]:
```suggestion
    "Pre-loaded libraries": "Preloaded Libraries",
```

**Review by juancarlosfarah — APPROVED** [review]
🎉
